version: '3.3'

services:
  jupyter:
    build:
      context: .
    ports:
      - "8888:8888"  # Porta padrão da interface web do Jupyter Notebook
        #      - "4040:4040"  # Porta padrão da interface web do Spark
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./config:/home/jovyan/.jupyter
    networks:
      - idpbigdata_network

  mongo:
    image: mongo:4.4-bionic
    container_name: mongo_service
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
      - ./db-seed:/db-seed
      - ./data:/datasets
    networks:
      - idpbigdata_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_service
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:mongo@mongo:27017/
    ports:
      - "8081:8081"
    networks:
      - idpbigdata_network
    depends_on:
      - mongo
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "mongo:27017", "--", "npm", "start"]

volumes:
  notebooks:
  data:
  config:
  dbdata:
  db-seed:          

networks:
  idpbigdata_network:
    driver: bridge
    name: idpbigdata_network

