version: '3.3'

services:
  mongo:
    image: mongo:4.4-bionic
    container_name: mongo_service
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
      - ./db-seed:/db-seed
      - ./data:/datasets
    networks:
      - idpbigdata_network

volumes:
  data:
  dbdata:
  db-seed:          

networks:
  idpbigdata_network:
    driver: bridge
    name: idpbigdata_network

