version: "3.3"

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=100M
    networks:
      - idpbigdata_network


  cassandra-web:
    image: strate/cassandra-web
    container_name: cassandra-web-container
    ports:
      - "3000:3000"
    environment:
      - CASSANDRA_HOSTS=cassandra
      - CASSANDRA_PORT=9042
    depends_on:
      - cassandra
    networks:
      - idpbigdata_network

networks:
  idpbigdata_network:
    driver: bridge
    name: idpbigdata_network
