version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - $HOME/redis/data:/data
    networks:
      - idpbigdata_network
  web:
    build: .
    ports:
      - "6000:6000"
    depends_on:
      - redis
    networks:
      - idpbigdata_network
networks:
  idpbigdata_network:
    external: true
